FROM elasticsearch:7.9.2

ENV HTTPS_PROXY=http://proxy.rd.francetelecom.fr:8080
ENV HTTP_PROXY=http://proxy.rd.francetelecom.fr:8080
#ENV HTTP_PROXY=http://10.193.21.110:8080
ENV https_proxy=http://proxy.rd.francetelecom.fr:8080
ENV http_proxy=http://proxy.rd.francetelecom.fr:8080
ENV NO_PROXY=registry.gitlab.tech.orange,registry.forge.orange-labs.fr,localhost,127.0.0.1

RUN ES_JAVA_OPTS="-Dhttp.proxyHost=proxy.rd.francetelecom.fr -Dhttp.proxyPort=8080 -Dhttps.proxyHost=proxy.rd.francetelecom.fr -Dhttps.proxyPort=8080" /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu
