FROM elasticsearch:7.9.2

ENV HTTPS_PROXY=http://proxy.rd.francetelecom.fr:8080
ENV HTTP_PROXY=http://proxy.rd.francetelecom.fr:8080
#ENV HTTP_PROXY=http://10.193.21.110:8080
ENV https_proxy=http://proxy.rd.francetelecom.fr:8080
ENV http_proxy=http://proxy.rd.francetelecom.fr:8080
ENV NO_PROXY=registry.gitlab.tech.orange,registry.forge.orange-labs.fr,localhost,127.0.0.1

RUN /bin/elasticsearch-plugin install analysis-icu
